### ISSUE TITLE
Any reason why you abs function only works with integers and floats?

### ISSUE THREAD

**Issue by KleinerNull** [mingrammer/funmath#2]
I mean Fractions, Decimals and complex numbers also have an absolute value. (all are built-in data types)

**Comment by mingrammer** [comment]
Hi KleinerNull! I just did not consider it. It's my mistakes.

So I'll update the `abs` function to accept the any numeric values.

Thank you very much.

**Comment by mingrammer** [comment]
When done, I'll inform you in here

**Comment by mingrammer** [comment]
I've done with https://github.com/mingrammer/funmath/commit/826602291461167150eefa973c719ac2cfaf937f
